server:
  port: 8888

spring:
  application:
    name: config-serverr

  cloud:
    config:
      server:
        git:
          uri: https://github.com/anuragsingh7011/microservices-sys.git
          default-label: main
          search-paths: /config-data
          clone-on-start: true
